### ISSUE TITLE
Replicate Table from publication 'A practical solution to...'

### ISSUE THREAD

**Issue by Al-Murphy** [kdzimm/hierarchicell#2]
Hi,

Thanks for making this R package. I was hoping to use it to replicate the table 1 from your publication 'A practical Solution to pseudoreplication bias' found here:

https://www.nature.com/articles/s41467-021-21038-1/tables/1

I think I know which commands to use (see below) but the type 1 errors I get when I run this is very different to the table (note that based on my parameters below I think it should match N ind = 10, N cells = 5). Perhaps I need to use a different input dataset rather than the default to create the simulated data? Or perhaps I am using the incorrect number of genes?

My code (output is in a comment below the command call):
```
gene_counts_filtered <- hierarchicell::filter_counts()
data_summ <- hierarchicell::compute_data_summaries(gene_counts_filtered, type = "Norm")
#04 compute error
error_hierarchicell(data_summ,
                    method = "Pseudobulk_mean",
                    n_genes = 1000,
                    n_per_group = 10,
                    cells_per_case = 50,
                    cells_per_control = 50,
                    ncells_variation_type = "Poisson",
                    pval = 0.05,
                    foldchange = 2)
#Type 1 error for 0.05 is: 0.954653937947494

error_hierarchicell(data_summ,
                    method = "Pseudobulk_sum",
                    n_genes = 1000,
                    n_per_group = 10,
                    cells_per_case = 50,
                    cells_per_control = 50,
                    ncells_variation_type = "Poisson",
                    pval = 0.05,
                    foldchange = 2)
#Type 1 error for 0.05 is: 0.949450549450549

error_hierarchicell(data_summ,
                    method = "MAST_RE",
                    n_genes = 1000,
                    n_per_group = 10,
                    cells_per_case = 50,
                    cells_per_control = 50,
                    ncells_variation_type = "Poisson",
                    pval = 0.05,
                    foldchange = 2)
#Type 1 error for 0.05 is: 0.997429305912596

error_hierarchicell(data_summ,
                    method = "GLM_tweedie",
                    n_genes = 1000,
                    n_per_group = 10,
                    cells_per_case = 50,
                    cells_per_control = 50,
                    ncells_variation_type = "Poisson",
                    pval = 0.05,
                    foldchange = 2)
#Type 1 error for 0.05 is: 0.516703786191537
```

**Comment by kdzimm** [comment]
Allen,

Thanks for reaching out. You should not need to use a different dataset than the default. Try fixing your foldchanges from 2 to 1 (want to be simulating under the null to get your type 1 error, here you are actually estimating power for a foldchange of 2). After you alter your foldchange to 1, your results should align more closely with table 1 from the manuscript, albeit with some random noise. If they do not, feel free to touch base again. Take good care!

Kip

**Comment by Al-Murphy** [comment]
Hi kip,

Thanks that definitely appears closer. Also was it 1000 genes that was used in the paper too? Or more?

Thanks,
Alan.

**Comment by kdzimm** [comment]
250,000. But was done in chunks of 5000.

**Comment by Al-Murphy** [comment]
So just done for 5,000 genes 50 times and then the score averaged across those 50 runs?

**Comment by kdzimm** [comment]
Yes, that's correct!
