### ISSUE TITLE
Compute_data_summaries fails to run

### ISSUE THREAD

**Issue by JoeTandurella** [kdzimm/hierarchicell#5]
Hi all,

I have been experiencing this issue for a while now without any luck -- when running compute_data_summaries on my imputed counts matrix, I receive the following error: "Error in tapply(a, expr[, 2], function(a) { : arguments must have same length".

Traceback includes: 
6. stop("arguments must have same length")
5. tapply(a, expr[, 2], function(a) { stats::var(a[a != 0]) })
4. FUN(X[[i]], ...)
3. lapply(X = X, FUN = FUN, ...)
2. sapply(expr[, c(-1, -2)], computevar)
1. compute_data_summaries(imputed_vals)

My imputed_vals object is a Large matrix of 36601 x 669. 

Any advice would be extremely helpful. Thanks in advance!

Best,
Joe Tandurella

**Comment by kdzimm** [comment]
Hey Joe,

What does your imputed counts matrix look like before you supply it to the compute_data_summaries step? Have you passed it through the "filter_counts" step? Is it first column Cell_ID, second column Individual_ID, and then a lot of GeneIDs? Is it a data.frame?

Thanks,

Kip

**Comment by JoeTandurella** [comment]
Hi Kip thanks for the fast response! That is most likely the issue. Prior to this, I was not able to find the vignette with the proper formatting -- I used a basic counts matrix format (genes as row names, cells as column names). Let me reformat and I'll let you know if the issue persists. Thanks again!

Edit --

Hi Kip, once reformatting and passing through filter_counts, the issue is resolved from what I can tell. It's currently running, but returning NA's. Could it have something to do with the use of imputed values so the expression levels are potentially relatively low even after running filter_counts? Also, filter_counts was also outputting NA when including the CellID and IndicidualID columns, so I ran it without them and added them after.  Not quite sure why this is happening.

**Comment by kdzimm** [comment]
@JoeTandurella what thresholds are you specifying for your filter_counts procedure? The defaults? When you say the imputed values are relatively low - how low exactly? Are these raw counts? Or TPMs or something similar? Just check to make sure you are not filtering out everything.

How many unique individualIDs do you have? The filter_counts should work with those columns. Something is not working correctly there. Hopefully we can figure it out. It may be a bug on my end.

**Comment by JoeTandurella** [comment]
Yes I used the defaults and my imputed values ranged from 0,0.003,...,115. I believe I have remedied that error -- seems as though my columns were losing their class when converting to a data frame (all became characters rather than characters and numerical). Now I am receiving an error when running power_hierarchicell:

> power_hierarchicell(data_summaries, n_genes = 100, n_per_group = 4000)

<simpleError in optim(par = vstart, fn = fnobj, fix.arg = fix.arg, obs = data,     gr = gradient, ddistnam = ddistname, hessian = TRUE, method = meth,     lower = lower, upper = upper, ...): non-finite value supplied by optim>

Error in fitdistrplus::fitdist(data_summaries$DropOut, "gamma", method = "mle") : 
  the function mle failed to estimate the parameters, 
                with the error code 100

**Comment by kdzimm** [comment]
@JoeTandurella can you run the "approximate_gene_drop" function on your data_summaries file? With plot=T? It will give you the same error again likely, but there will be a plot in your working directory. What does that distribution look like?

**Comment by JoeTandurella** [comment]
Yes same error and it does not produce a distinguishable plot:
![gene_drop](https://user-images.githubusercontent.com/87984340/140943118-55ea6397-28bc-4399-b948-00cbb548388a.png)
 
I checked the data_summaries[[2]][["DropOut"]] object to visualize and it is full of 0's.

**Comment by kdzimm** [comment]
Very odd. It looks like you have a uniform distribution of dropouts between 0.5 and 1.5... these should be between 0-1 as you can only ever have 0% missing or 100% missing... I'll have a look at my code and get back to you in the next day or two. Sorry for this. There are components of the package we are still hoping to smooth out to make things more user friendly.

**Comment by JoeTandurella** [comment]
okay no worries, thanks! I really appreciate it.

**Comment by kdzimm** [comment]
also, just a heads up. I noticed you had n_per_group=4000. That is 4000 individuals (8000 total), not 4000 cells per individual. Is that correct? That is a massive amount of data and this power calculator would take a verrrry long time to compute just a single estimate of power.

**Comment by JoeTandurella** [comment]
Yes we wanted to see the power of 4k cells per condition! I'm running it all again now using the normalized counts and it seems to be working fine. It might just be an issue with using imputed counts.

**Comment by kdzimm** [comment]
Do you have independent experimental units or are these cells from a cell culture?

**Comment by JoeTandurella** [comment]
These are cells from cell culture under two conditions.

**Comment by kdzimm** [comment]
@JoeTandurella I am going to close this issue for now, but please do not hesitate to reach out again.
